export const orderDetailsConfig = {
  fields: [
    {
      name: "order_id",
      labelText: "Order ID",
      key: "id",
      tag: "input",
      type: "number",
      disabled: true,
    },
    {
      name: "order_code",
      labelText: "Order Code",
      placeholderText: "Generated in backend...",
      key: "order_code",
      tag: "input",
      type: "text",
      disabled: true,
      required: true,
    },
    {
      name: "Customer Name",
      labelText: "Customer Name",
      key: "name",
      tag: "select",
      source: "customers",
      disabled: false,
      required: true,
    },
    {
      name: "status",
      labelText: "Order Status",
      key: "status",
      tag: "select",
      source: "order_status",
      disabled: false,
      required: true,
    },
    {
      name: "total_price",
      labelText: "Total Price",
      placeholderText: "Calculated...",
      key: "total_price",
      tag: "input",
      type: "number",
      step: 0.01,
      disabled: true,
      required: true,
    },
    {
      name: "date_added",
      labelText: "Order Date",
      key: "date_added",
      tag: "input",
      type: "date",
      readonly: true,
      required: true,
    },
  ],
};

export const orderAddressConfig = {
  fields: [
    {
      name: "first_name",
      labelText: "First Name",
      key: "first_name",
      tag: "input",
      type: "text",
      disabled: false,
      required: true,
    },
    {
      name: "last_name",
      labelText: "Last Name",
      key: "last_name",
      tag: "input",
      type: "text",
      disabled: false,
      required: true,
    },
    {
      name: "email",
      labelText: "Email",
      key: "email",
      tag: "input",
      type: "email",
      disabled: false,
      required: true,
    },
    {
      name: "phone_number",
      labelText: "Phone Number",
      key: "phone_number",
      tag: "input",
      type: "text",
      disabled: false,
      required: true,
    },
    {
      name: "state",
      labelText: "State",
      key: "state",
      tag: "input",
      type: "text",
      disabled: false,
      required: true,
    },
    {
      name: "city",
      labelText: "City",
      key: "city",
      tag: "input",
      type: "text",
      disabled: false,
      required: true,
    },
    {
      name: "address_line1",
      labelText: "Address Line 1",
      key: "address_line1",
      tag: "input",
      type: "text",
      disabled: false,
      required: true,
    },
    {
      name: "address_line2",
      labelText: "Address Line 2",
      key: "address_line2",
      tag: "input",
      type: "text",
      disabled: false,
      required: true,
    },
    {
      name: "additional_notes",
      labelText: "Additional Notes",
      key: "additional_notes",
      tag: "textarea",
      disabled: false,
      required: false,
    },
  ],
};
