export const orderFormConfigs = {
  fields: [
    {
      name: "order_id",
      labelText: "Order ID",
      key: "id",
      tag: "input",
      type: "number",
      disabled: true,
    },
    {
      name: "order_code",
      labelText: "Order Code",
      key: "order_code",
      tag: "input",
      type: "text",
      disabled: true,
      required: true,
    },
    {
      name: "Customer Name",
      labelText: "Customer Name",
      key: "name",
      tag: "input",
      type: "text",
      disabled: false,
      required: true,
    },
    {
      name: "Email",
      labelText: "Email",
      key: "email",
      tag: "input",
      type: "email",
      disabled: false,
      required: true,
    },
    {
      name: "Phone_number",
      labelText: "Phone Number",
      key: "phone_number",
      tag: "input",
      type: "text",
      disabled: false,
      required: true,
    },
    {
      name: "status",
      labelText: "Order Status",
      key: "status",
      tag: "select",
      source: "order_status",
      disabled: false,
      required: true,
    },
    {
      name: "total_price",
      labelText: "Total Price",
      key: "total_price",
      tag: "input",
      type: "number",
      step: 0.01,
      disabled: false,
      required: true,
    },
    {
      name: "date_added",
      labelText: "Order Date",
      key: "date_added",
      tag: "input",
      type: "text",
      disabled: true,
      required: true,
    },
  ],
};
