export const bookFormConfigs = {
  fields: [
    {
      name: "Book_id",
      labelText: "ID",
      key: "id",
      tag: "input",
      type: "number",
      disabled: true,
    },
    {
      name: "ISBN",
      labelText: "ISBN",
      key: "isbn",
      tag: "input",
      type: "text",
      disabled: false,
      required: true,
    },
    {
      name: "Sku",
      labelText: "SKU",
      key: "sku",
      tag: "input",
      type: "text",
      disabled: false,
      required: true,
    },
    {
      name: "Title",
      labelText: "Title",
      key: "title",
      tag: "input",
      type: "text",
      disabled: false,
      required: false,
    },
    {
      name: "Language",
      labelText: "Language",
      key: "language",
      tag: "select",
      source: "languages",
      disabled: false,
      required: true,
    },
    {
      name: "Author",
      labelText: "Author",
      key: "author_id",
      tag: "select",
      source: "authors",
      disabled: false,
      required: true,
    },
    {
      name: "Format",
      labelText: "Format",
      key: "format_id",
      tag: "select",
      source: "formats",
      disabled: false,
      required: true,
    },
    {
      name: "Cover",
      labelText: "Cover",
      key: "cover_image",
      tag: "input",
      type: "file",
      disabled: false,
      required: false,
    },
    {
      name: "Description",
      labelText: "Description",
      key: "description",
      tag: "textarea",
      disabled: false,
      required: false,
    },
    {
      name: "Genre",
      labelText: "Genre",
      key: "genre_id",
      tag: "select",
      source: "genres",
      disabled: false,
      required: true,
    },
    {
      name: "Quantity",
      labelText: "Stock Quantity",
      key: "stock_quantity",
      tag: "input",
      type: "number",
      disabled: false,
      required: true,
    },
    {
      name: "Price",
      labelText: "Base Price",
      key: "price",
      tag: "input",
      type: "number",
      step: "0.01",
      disabled: false,
      required: true,
    },
    {
      name: "Discount",
      labelText: "Apply Discount",
      key: "is_onSale",
      tag: "input",
      type: "checkbox",
      disabled: false,
      required: false,
    },
    {
      name: "Discount_Percentage",
      labelText: "Discount Percentage",
      containerClass: "discount-info",
      key: "discount_percentage",
      placeholder: "10%-100%",
      tag: "input",
      type: "number",
      step: "10",
      min: "10",
      max: "100",
      disabled: false,
      required: false,
    },
  ],
};
