export const AddressConfig = {
  fields: [
    {
      name: "first_name",
      labelText: "First Name",
      key: "first_name",
      tag: "input",
      type: "text",
      disabled: false,
      required: true,
    },
    {
      name: "last_name",
      labelText: "Last Name",
      key: "last_name",
      tag: "input",
      type: "text",
      disabled: false,
      required: true,
    },
    {
      name: "email",
      labelText: "Email",
      key: "email",
      tag: "input",
      type: "email",
      disabled: false,
      required: true,
    },
    {
      name: "phone_number",
      labelText: "Phone Number",
      key: "phone_number",
      tag: "input",
      type: "text",
      disabled: false,
      required: true,
    },
    {
      name: "state",
      labelText: "State",
      key: "state",
      tag: "input",
      type: "text",
      disabled: false,
      required: true,
    },
    {
      name: "city",
      labelText: "City",
      key: "city",
      tag: "input",
      type: "text",
      disabled: false,
      required: true,
    },
    {
      name: "address_line1",
      labelText: "Address Line 1",
      key: "address_line1",
      tag: "input",
      type: "text",
      disabled: false,
      required: true,
    },
    {
      name: "address_line2",
      labelText: "Address Line 2",
      key: "address_line2",
      tag: "input",
      type: "text",
      disabled: false,
      required: false,
    },
    {
      name: "additional_notes",
      labelText: "Additional Notes",
      key: "additional_notes",
      tag: "textarea",
      disabled: false,
      required: false,
    },
  ],
};
